console.log("we love javascript")
console.log("we love javascript")
console.log("we love javascript")
console.log("we love javascript")
console.log("we love javascript")
console.log("we love javascript")
console.log("we ")